## JAVASCRIPT: Weather App
FrederickMih/WEATHER-APP pull request #3
Opened 2021-06-13 05:55 UTC by FrederickMih

## THE WEATHER APP
 In this branch,
- I installed and configured webpack
- I wrote functions that fetch some vital information from a weather map API such as the temperature(degree celsius or Fahrenheit ), humidity, weather description from a particular city of a country.
- I equally make use of the giphy API images to describe how the weather condition may look.

2021-06-13 07:58 UTC, taiwo2 requested changes
# STATUS: CHANGES REQUIRED ⚠️ 🚧
@FrederickMih, Weldone for the job done. Almost all the requirement is met but few changes is requested to get your project approved.

- [ ] It changes its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
- [ ] kindly add the screenshot of your app to your readme and in your setup section kindly use 'npm run start' to run your app.
- [ ] I can't run your app with the script provided in your `package.json` ,Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/)).please replace the script wth this :
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

### Once specific changes made kindly request for another review

2021-06-13 14:29 UTC, taiwo2 requested changes
# STATUS : CHANGES REQUIRED ♻️ 
@FrederickMih  Good day, thanks for implementing some part of the requested cahnges,however changes is required to get your project approved
### highlight
kindly add the screenshot of your app to your readme
### To improve
- [ ] It changes its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app)).

- [ ] Kindly add `webpack.config.js` to your root file and remove `webpack.common.js`,`webpack.dev.js`,`webpackprod.js`. here is how to install webpack.config.js [link](https://webpack.js.org/guides/getting-started/#using-a-configuration) and you can replace ` "start": "webpack-dev-server --mode development --open" with
`   `"start": "webpack serve --mode development --open"` as its noticed its not working
- [ ] Your set up section still missing  `npm start` kindly fix it

.

2021-06-14 10:58 UTC, mikenath223 requested changes
### Hello @FrederickMih  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

- [ ] After the weather data loads the form to input a new city gets hidden due to a styling bug. Please check and fix it.

- Please refer to the other comment on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-06-14 11:00 UTC, mikenath223 commented on README.md
> +
- [ ] As requested in the previous review please add `npm start` after `npm install` instruction as the command ensures webpack compiles the project before opening it.

2021-06-14 12:16 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-06-14 12:28 UTC, merged